### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCMaskedView" was not found in the UIManager.

### ISSUE THREAD

**Issue by mmosayed** [react-native-community/react-native-masked-view#11]
```
Unhandled JS Exception: Invariant Violation: Invariant Violation: requireNativeComponent: "RNCMaskedView" was not found in the UIManager.

This error is located at:
    in RNCMaskedView (at MaskedView.ios.js:73)
```

I keep getting this error when using the community version. But when I used the Deprecated MaskedViewIOS it works.

I've done `react-native link @react-native-community/masked-view` successfully. So not sure what's wrong

Versions:
- @react-native-community/masked-view: ^0.0.5
- react: 16.8.3
- react-native: 0.59.8

**Comment by FonDorn** [comment]
After `react-native link @react-native-community/masked-view` you must relaunch application like `react-native run-ios`

**Comment by mmosayed** [comment]
Thanks for getting back so quick! I've done that. Closed and cleaned my build. Tried compiling directly using XCode and also tried using `react-native run-ios`.

When I'm installing through yarn I do get the following warning:
`warning " > @react-native-community/masked-view@0.0.5" has incorrect peer dependency "react-native@^0.57".`...but it still successfully installs the dependency

**Comment by mmosayed** [comment]
Hey I noticed you've closed this issue, can you please tell me why?

**Comment by FonDorn** [comment]
Your problem was that you didn’t rebuild and restart application after linked library. This issues is closed. Whats about warning - it is just warning and does not affect the operation of the module. This warning will fixed in next version.

**Comment by mmosayed** [comment]
No I just explained, I've tried all of that. No luck. Still crashes and get the same error. 

> I've done that. Closed and cleaned my build. Tried compiling directly using XCode and also tried using `react-native run-ios`

That is why I am baffled.

**Comment by mmosayed** [comment]
Okay, I installed the dependency on a fresh RN project and moved over my /src files. Now it seems to be working. Thanks

**Comment by slonv23** [comment]
Same happening to me. Is there any way to resolve this without creating new RN project?

**Comment by RymaTech** [comment]
Delete Build, 
yarn add @react-native-community/masked-view,
react-native link @react-native-community/masked-view,
cd ios,
pod install,
restart the simulator

**Comment by iDuuck** [comment]
Also had the problem and though this would be automatically linked since the new `react-native` update. Nevertheless, I needed to link it using `react-native link @react-native-community/masked-view`.

**Comment by bitcrumb** [comment]
Note that I got this error as well (when running on Android). The solution for me was to run `./gradlew clean` inside the `/android` folder.

**Comment by kalpeshmuthe07** [comment]
Invariant Violation: requireNativeComponent: "RNCMaskedView" was not found in the UIManager.

**Comment by JimTeva** [comment]
I had the same problem on Android and finally found a solution.
In MainApplication.java file (under android/app/src/main/java/com/projectName):
```
import org.reactnative.maskedview.RNCMaskedViewPackage;
...
protected List<ReactPackage> getPackages() {
    // Add additional packages you require here
    return Arrays.<ReactPackage>asList("... your other packages here", new RNCMaskedViewPackage());
  }
```

**Comment by rogerkerse** [comment]
None of it seem to work for me on iOS and RN 71

**Comment by thidasapankaja** [comment]
Facing the same with Android trying to use `react-native-skeleton-placeholder` . Tried the approach @JimTeva suggested, but then the app doesn't build. I'm getting an error then

**Comment by Nader-CS** [comment]
i have the same problem with build release

**Comment by CatalinTudose** [comment]
any news on this?

**Comment by mhsfh** [comment]
facing same issue on ios with react-native `0.74.2`
